kind: ProductOfExpertsAggregatorConfig
image_similarity_matrix_path: /tmp/similarities/baseline_seattle.pt
landmark_similarity_matrix_path: /tmp/similarities/proper_noun_embedding_seattle.pt
tau_img: 0.25
tau_lm: 0.25
